import os
import time
import random
delay = random.randint(1, 6)

def loading():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("iniciando cadastro")
    print("⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛")
    time.sleep(delay)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("iniciando cadastro")
    print("🟦🟦⬛⬛⬛⬛⬛⬛⬛⬛⬛")
    time.sleep(delay)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("iniciando cadastro")
    print("🟦🟦🟦⬛⬛⬛⬛⬛⬛⬛⬛")
    time.sleep(delay)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("iniciando cadastro")
    print("🟦🟦🟦🟦🟦🟦🟦⬛⬛⬛⬛")
    time.sleep(delay)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("iniciando cadastro")
    print("🟦🟦🟦🟦🟦🟦🟦🟦🟦⬛⬛")
    time.sleep(delay)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("iniciando cadastro")
    print("🟦🟦🟦🟦🟦🟦🟦⬛⬛⬛⬛")
    time.sleep(delay)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("iniciando cadastro")
    print("🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦")
    time.sleep(0.5)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("==============")
