import os
import time
import random
delay = random.randint(1, 2)

def loading():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("|𝙸𝙽𝙸𝙲𝙸𝙰𝙽𝙳𝙾 𝙲𝙰𝙳𝙰𝚂𝚃𝚁𝙾")
    print("|⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛")
    time.sleep(delay)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("|𝙸𝙽𝙸𝙲𝙸𝙰𝙽𝙳𝙾 𝙲𝙰𝙳𝙰𝚂𝚃𝚁𝙾")
    print("|🟦🟦⬛⬛⬛⬛⬛⬛⬛⬛⬛")
    time.sleep(delay)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("|𝙸𝙽𝙸𝙲𝙸𝙰𝙽𝙳𝙾 𝙲𝙰𝙳𝙰𝚂𝚃𝚁𝙾")
    print("|🟦🟦🟦⬛⬛⬛⬛⬛⬛⬛⬛")
    time.sleep(delay)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("|𝙸𝙽𝙸𝙲𝙸𝙰𝙽𝙳𝙾 𝙲𝙰𝙳𝙰𝚂𝚃𝚁𝙾")
    print("|🟦🟦🟦🟦🟦🟦🟦⬛⬛⬛⬛")
    time.sleep(delay)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("|𝙸𝙽𝙸𝙲𝙸𝙰𝙽𝙳𝙾 𝙲𝙰𝙳𝙰𝚂𝚃𝚁𝙾")
    print("|🟦🟦🟦🟦🟦🟦🟦🟦🟦⬛⬛")
    time.sleep(delay)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("|𝙸𝙽𝙸𝙲𝙸𝙰𝙽𝙳𝙾 𝙲𝙰𝙳𝙰𝚂𝚃𝚁𝙾")
    print("|🟦🟦🟦🟦🟦🟦🟦⬛⬛⬛⬛")
    time.sleep(delay)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("|𝙸𝙽𝙸𝙲𝙸𝙰𝙽𝙳𝙾 𝙲𝙰𝙳𝙰𝚂𝚃𝚁𝙾")
    print("|🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦⬛")
    time.sleep(delay)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("|𝙸𝙽𝙸𝙲𝙸𝙰𝙽𝙳𝙾 𝙲𝙰𝙳𝙰𝚂𝚃𝚁𝙾")
    print("|🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦🟦")
    time.sleep(0.5)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("|==============")
